struct Movie: Codable {
    let id: Int
    let title: String
    let year: Int
    let genre: String
    let posterImage: String
    let description: String
    let director: String
    let rating: Double
    
    static let mockData: [Movie] = [
        Movie(id: 1,
             title: "Inception",
             year: 2010,
             genre: "Sci-Fi/Action",
             posterImage: "https://image.tmdb.org/t/p/w500/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg",
             description: "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
             director: "Christopher Nolan",
             rating: 8.8),
        Movie(id: 2,
             title: "The Shawshank Redemption",
             year: 1994,
             genre: "Drama",
             posterImage: "https://image.tmdb.org/t/p/w500/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg",
             description: "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
             director: "Frank Darabont",
             rating: 9.3),
        Movie(id: 3,
             title: "The Dark Knight",
             year: 2008,
             genre: "Action/Drama",
             posterImage: "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
             description: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
             director: "Christopher Nolan",
             rating: 9.0),
        Movie(id: 4,
             title: "Pulp Fiction",
             year: 1994,
             genre: "Crime/Drama",
             posterImage: "https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
             description: "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
             director: "Quentin Tarantino",
             rating: 8.9),
        Movie(id: 5,
             title: "Forrest Gump",
             year: 1994,
             genre: "Drama/Romance",
             posterImage: "https://image.tmdb.org/t/p/w500/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg",
             description: "The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold from the perspective of an Alabama man with an IQ of 75, whose only desire is to be reunited with his childhood sweetheart.",
             director: "Robert Zemeckis",
             rating: 8.8),
        Movie(id: 6,
             title: "The Matrix",
             year: 1999,
             genre: "Sci-Fi/Action",
             posterImage: "https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg",
             description: "A computer programmer discovers that reality as he knows it is a simulation created by machines, and joins a rebellion to break free from the system.",
             director: "The Wachowskis",
             rating: 8.7),
        Movie(id: 7,
             title: "Goodfellas",
             year: 1990,
             genre: "Crime/Drama",
             posterImage: "https://image.tmdb.org/t/p/w500/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg",
             description: "The story of Henry Hill and his life in the mob, covering his relationship with his wife Karen Hill and his mob partners Jimmy Conway and Tommy DeVito in the Italian-American crime syndicate.",
             director: "Martin Scorsese",
             rating: 8.7),
        Movie(id: 8,
             title: "The Silence of the Lambs",
             year: 1991,
             genre: "Thriller/Crime",
             posterImage: "https://image.tmdb.org/t/p/w500/rplLJ2hPcOQmkFhTqUte0MkEaO2.jpg",
             description: "A young F.B.I. cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer, a madman who skins his victims.",
             director: "Jonathan Demme",
             rating: 8.6),
        Movie(id: 9,
             title: "Fight Club",
             year: 1999,
             genre: "Drama/Thriller",
             posterImage: "https://image.tmdb.org/t/p/w500/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg",
             description: "An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more.",
             director: "David Fincher",
             rating: 8.8),
        Movie(id: 10,
             title: "The Green Mile",
             year: 1999,
             genre: "Drama/Fantasy",
             posterImage: "https://image.tmdb.org/t/p/w500/velWPhVMQeQKcxggNEU8YmIo52R.jpg",
             description: "The lives of guards on Death Row are affected by one of their charges: a black man accused of child murder and rape, yet who has a mysterious gift.",
             director: "Frank Darabont",
             rating: 8.6)
    ]
}
